name: Create Apt Release

on:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build Package
        run: |
          # Set release version based on github ref
          RELEASE_VERSION=v0.1.2
          # RELEASE_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev )
          sed -i "s/RELEASE_VERSION/${RELEASE_VERSION}/" control

          # Open up permissions on all files so no permissions issues happen
          sudo chmod 777 -R .
          curl -L https://github.com/splicemachine/splicectl/releases/download/$RELEASE_VERSION/splicectl_linux_amd64.tar.gz | tar -xz -C .
          cp ./splicectl_linux_amd64/splicectl ./splicectl

          # Create debian folder
          mv splicectl splicectl.tmp
          mkdir -p splicectl/usr/bin/
          mkdir -p splicectl/DEBIAN/	
          cp control splicectl/DEBIAN/control
          mv splicectl.tmp splicectl/usr/bin/splicectl
          dpkg-deb --build splicectl
          ls -ltra
          ls -ltra splicectl
          ls -ltra splicectl/DEBIAN
          ls -ltra splicectl/usr
          ls -ltra splicectl/usr/bin
      # - name: Build Debian Package Buster
      #   uses: nylas/build-dpkg-buster@v1
