name: Create Apt Release

on:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  debianrelease:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build Debian Package Buster
        uses: nylas/build-dpkg-buster@v1
      - name: List stuff
        runs: ls -ltra
