name: Create Arch Linux Release

on:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Build app
        run: go build .
      -
        name: list dir
        run: ls -ltra
      -
        name: cat pkgb
        run: cat PKGBUILD
      - name: Arch makepkg
        uses: py7hon/arch-makepkg@v0.0.2

      -
        name: list dir
        run: ls -ltra
      -
        name: Upload to S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: s3://splice-releases/splicectl/aur/
          source_dir: $HOME/arch-packages
  test:
    runs-on: ubuntu-latest
    needs: release
    steps:
      -
        name: Add Repo to pacman, install and test splicectl
        run: |
          echo -e "[splice]\nSigLevel = Optional TrustAll\nServer = https://splice-releases.s3.amazonaws.com/splicectl/aur/" >> /etc/pacman.conf
          sudo pacman -Sy splicectl
          echo RELEASE_TAG=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}
          splicectl version | grep ${{ env.RELEASE_TAG }}
